// <auto-generated />
using System;
using ApiToDoList.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiToDoList.Migrations
{
    [DbContext(typeof(ClsTodoList))]
    [Migration("20221030220040_Tareas Table")]
    partial class TareasTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiToDoList.Models.ClsBaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CreateTasks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAtTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleteTasks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAtTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpDateAtTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateTasks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TasksTable");
                });
#pragma warning restore 612, 618
        }
    }
}
