USE [master]
GO

/****** Object:  Database [TodoListDB]    Script Date: 29/10/2022 16:39:02 ******/
CREATE DATABASE [TodoListDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TodoListDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TodoListDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TodoListDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TodoListDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TodoListDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TodoListDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TodoListDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TodoListDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TodoListDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TodoListDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TodoListDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TodoListDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TodoListDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TodoListDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TodoListDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TodoListDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TodoListDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TodoListDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TodoListDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TodoListDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TodoListDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TodoListDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TodoListDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TodoListDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TodoListDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TodoListDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [TodoListDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TodoListDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TodoListDB] SET  MULTI_USER 
GO

ALTER DATABASE [TodoListDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TodoListDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TodoListDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TodoListDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TodoListDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TodoListDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TodoListDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TodoListDB] SET  READ_WRITE 
GO


INSERT INTO [dbo].[TasksTable] (CreateTasks, [IsDeleted])
VALUES 
( 'Crear API para Mi Aplicación To Do List', 0),
( 'Leer Libro', 0),
( 'Aprender Angular', 0);

SELECT * FROM [dbo].[TasksTable]